### ISSUE TITLE
Installation and Usage steps needed for testing

### ISSUE THREAD

**Issue by sleekmike** [nalbion/whisper-server#1]
Hi, I just came across your repo and it looks amazing!

I would like to know what were your motivations and reasons for using Server Sent Events and gRPC for realtime streaming from microphone over Web-socket or webRTC.

I also want to try it out but the installation and usage/demo steps seems to be missing.
Please add a simple usage/demo script that depicts how one can use microphone and audio file. Thanks!

**Comment by nalbion** [comment]
I might need to make it more clear that this is intended as a local single-user server so that non-Python programs can use Whisper. 

The Python process owns the microphone and delivers the text transcriptions in real-time. Web-socket or webRTC would make more sense for a multi-user server where the audio was sent to the server for processing.

I've added CLI args & support for `--help`

**Comment by sleekmike** [comment]
Ok I understand your reasons now, I will give it a try and let you know. 
Good work!
